TechLife.CSDLMoiTruong.App/Component/PagingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TechLife.CSDLMoiTruong.App.Models;
using TechLife.CSDLMoiTruong.Common;
using TechLife.CSDLMoiTruong.Common.Result;

namespace TechLife.CSDLMoiTruong.App.Component
{
    public class PagingViewComponent : ViewComponent
    {
        private async Task OptionPage(int total = 0)
        {
            await Task.Run(() =>
            {
                var list = new List<SelectListItem>();
                if (total >= SystemConstants.pageSize)
                {
                    list.Add(new SelectListItem() { Text = "" + SystemConstants.pageSize + "", Value = SystemConstants.pageSize.ToString() });
                    list.Add(new SelectListItem() { Text = "30", Value = "30" });
                    list.Add(new SelectListItem() { Text = "60", Value = "60" });
                    list.Add(new SelectListItem() { Text = "90", Value = "90" });
                    list.Add(new SelectListItem() { Text = "120", Value = "120" });
                }

                ViewBag.listPage = list;
            });
        }

        public async Task<IViewComponentResult> InvokeAsync(PagedResultBase page)
        {
            var model = new PagingViewModel();

            model.PageIndex = page.PageIndex;
            model.Total = page.TotalRecords;
            model.PageSize = page.PageSize;

            await OptionPage(page.TotalRecords);

            return View("_Paging", model);
        }
    }
}

TechLife.CSDLMoiTruong.App/Controllers/LoaiCayTrongController.cs
using Microsoft.AspNetCore.Mvc;
using TechLife.CSDLMoiTruong.App.ApiClients;
using TechLife.CSDLMoiTruong.App.Extensions;
using TechLife.CSDLMoiTruong.Common.Result;
using TechLife.CSDLMoiTruong.Common;
using TechLife.CSDLMoiTruong.Service;
using TechLife.CSDLMoiTruong.Model.LoaiCayTrong;

namespace TechLife.CSDLMoiTruong.App.Controllers
{
    public class LoaiCayTrongController : BaseController
    {
        private readonly ILogger<LoaiCayTrongController> _logger;
        private readonly ILoaiCayTrongService _loaiCayTrongService;
        public LoaiCayTrongController(IUserApiClient userApiClient
            , ILogger<LoaiCayTrongController> logger
            , ILoaiCayTrongService loaiCayTrongService) : base(userApiClient, logger)
        {
            _logger = logger;
            _loaiCayTrongService = loaiCayTrongService;
        }

        public IActionResult Index(LoaiCayTrongGetPagingRequest request)
        {
            return View(request);
        }

        public async Task<IActionResult> List(LoaiCayTrongGetPagingRequest request)
        {
            try
            {
                var data = await _loaiCayTrongService.GetPagings(request);

                return PartialView(data);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return PartialView();
            }

        }

        [HttpGet]
        public IActionResult Create()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create(LoaiCayTrongCreateRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return IsValidResult();
                }

                var userId = User.GetUserId();
                request.UserId = userId != Guid.Empty ? userId : Guid.Parse("11111111-1111-1111-1111-111111111111");


                return await ActionResult(await _loaiCayTrongService.Create(request));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return ErrorResult();
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var data = await _loaiCayTrongService.GetById(Convert.ToInt32(SystemHashUtil.DecodeID(id, SystemConstants.AppSettings.Key)));
                var model = new LoaiCayTrongUpdateRequest()
                {
                    Name = data.Name,
                    Code = data.Code,
                    Description = data.Description,
                    Id = id
                };
                return PartialView(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return PartialView();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Edit(LoaiCayTrongUpdateRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return IsValidResult();
                }

                request.UserId = User.GetUserId();

                return await ActionResult(await _loaiCayTrongService.Update(request));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return ErrorResult();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(DeleteRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return IsValidResult();
                }

                request.UserId = User.GetUserId();

                return await ActionResult(await _loaiCayTrongService.Delete(request));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return ErrorResult();
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateStatus(UpdateStatusRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return IsValidResult();
                }

                request.UserId = User.GetUserId();

                return await ActionResult(await _loaiCayTrongService.UpdateStatus(request));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return ErrorResult();
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateOrder(UpdateOrderRequest request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return IsValidResult();
                }

                request.UserId = User.GetUserId();

                return await ActionResult(await _loaiCayTrongService.UpdateOrder(request));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Đã có lỗi xãy ra");

                return ErrorResult();
            }
        }
    }
}

TechLife.CSDLMoiTruong.App/Views/LoaiCayTrong/Create.cshtml
@model TechLife.CSDLMoiTruong.Model.LoaiCayTrong.LoaiCayTrongCreateRequest
@using TechLife.CSDLMoiTruong.Common;
<div class="modal-content">
    <form id="modal-form" enctype="multipart/form-data">
        <div class="modal-header">
            <h4 class="modal-title">Thêm mới loại cây trồng</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Code" class="form-label"></label>
                        <input asp-for="Code" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label"></label> <span class="text-danger">(*)</span>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Description" class="form-label"></label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            @Html.AntiForgeryToken()
            <button type="button" data-bs-dismiss="modal" class="btn btn-secondary">Đóng</button>
            <button type="submit" class="btn btn-success">Lưu</button>
        </div>
    </form>
    @{
        await Html.RenderPartialAsync("_ModalScript",
        new TechLife.CSDLMoiTruong.App.Models.ModalFormRequest()
            {
                FormId = "modal-form",
                UrlSubmit = "/LoaiCayTrong/Create",
                UrlPathLoadData = Context.Request.Query["resultUrl"],
                LoadDataId = "box-content"
            });
    }
</div>

TechLife.CSDLMoiTruong.App/Views/LoaiCayTrong/Edit.cshtml
@model TechLife.CSDLMoiTruong.Model.LoaiCayTrong.LoaiCayTrongUpdateRequest
@using TechLife.CSDLMoiTruong.Common;
<div class="modal-content">
    <form id="modal-form" enctype="multipart/form-data">
        <div class="modal-header">
            <h4 class="modal-title">Sửa thông tin loại cây trồng</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Code" class="form-label"></label>
                        <input asp-for="Code" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Code" class="text-danger"></span>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Name" class="form-label"> </label>  <span class="text-danger">(*)</span>
                        <input asp-for="Name" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="mb-3">
                        <label asp-for="Description" class="form-label"> </label>
                        <input asp-for="Description" class="form-control" autocomplete="off" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            @Html.AntiForgeryToken()
            <input type="hidden" asp-for="Id" />
            <button type="button" data-bs-dismiss="modal" class="btn btn-secondary">Đóng</button>
            <button type="submit" class="btn btn-primary">Lưu</button>
        </div>
    </form>
    @{
        await Html.RenderPartialAsync("_ModalScript",
        new TechLife.CSDLMoiTruong.App.Models.ModalFormRequest()
            {
                FormId = "modal-form",
                UrlSubmit = "/LoaiCayTrong/Edit",
                UrlPathLoadData = Context.Request.Query["resultUrl"],
                LoadDataId = "box-content"
            });
    }
</div>

TechLife.CSDLMoiTruong.App/Views/LoaiCayTrong/Index.cshtml
@using TechLife.CSDLMoiTruong.App.Extensions
@model TechLife.CSDLMoiTruong.Model.LoaiCayTrong.LoaiCayTrongGetPagingRequest
@{
    ViewData["Title"] = "Danh sách loại cây trồng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section id="widget-grid">
    <div class="row">
        <!-- NEW WIDGET START -->
        <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="jarviswidget" id="wid-id-groups" data-widget-colorbutton="false"
                 data-widget-deletebutton="false"
                 data-widget-editbutton="false">
                <header>
                    <span class="widget-icon"> <i class="fa fa-bank"></i> </span>
                    <h2>@ViewData["Title"]</h2>
                </header>
                <div>
                    <!-- widget edit box -->
                    <div class="jarviswidget-editbox">
                        <!-- This area used as dropdown edit box -->
                    </div>
                    <!-- end widget edit box -->
                    <!-- widget content -->
                    <div class="widget-body">
                        <form method="get">
                            <div class="padding-bottom-10">

                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="form-label">Từ khóa tìm kiếm:</label>
                                        <div class="input-group input-group-sm">
                                            <input class="form-control" asp-for="Keyword" autocomplete="off" placeholder="Nhập từ khóa tìm kiếm...">
                                            <button class="btn btn-primary" type="submit">
                                                <i class="fa fa-search" aria-hidden="true"></i>
                                                Tìm kiếm
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <button type="button" title="Thêm loại cây trồng" data-link="@Context.Request.GetRawUrl("/LoaiCayTrong/List/")" data-url="/LoaiCayTrong/Create/" data-toggle="modal" data-target="#modal" class="btn btn-success btn-sm popup"><i class="fa fa-plus-circle"></i> Thêm mới</button>
                                    </div>
                                </div>
                            </div>
                            <div id="box-content">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

@section scripts
    {
    <script type="text/javascript">
        $(document).ready(function () {
            let element = document.getElementById('box-content');
            loadContent('@Html.Raw(Context.Request.GetRawUrl("/LoaiCayTrong/List/"))', element);
            $("#status").on("change", function () {
                this.form.submit()
            });
            pageSetUp();
        });
    </script>
}

TechLife.CSDLMoiTruong.App/Views/LoaiCayTrong/List.cshtml
@using TechLife.CSDLMoiTruong.App.Extensions
@using TechLife.CSDLMoiTruong.Common;
@using TechLife.CSDLMoiTruong.Common.Result;
@model PagedResult<TechLife.CSDLMoiTruong.Model.LoaiCayTrong.LoaiCayTrongVm>
<div class="box">
    <!-- /.box-header -->
    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Tên loại cây trồng</th>
                        <th>Mã loại cây trồng</th>
                        <th width="10%" class="text-center">Vị trí</th>
                        <th width="10%" class="text-center">Áp dụng</th>
                        <th width="20%" class="text-center">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model != null && Model.Items != null && Model.Items.Count() > 0)
                        {
                            int stt = 0;
                            foreach (var d in Model.Items)
                            {
                                <tr>
                                    <td class="align-middle"><strong>@(++stt). @d.Name</strong></td>
                                    <td class="align-middle"><strong>@d.Code</strong></td>
                                    <td class="text-center align-middle">
                                        <input type="number" min="1" value="@d.Order" data-url="/LoaiCayTrong/UpdateOrder/" data-id="@SystemFunctions.EncodeId(d.Id)" class="form-control form-control-sm txtOrder text-right" />
                                    </td>
                                    <td class="text-center align-middle">
                                        <input type="checkbox" data-url="/LoaiCayTrong/UpdateStatus/" data-id="@SystemFunctions.EncodeId(d.Id)" class="chStatus" checked="@d.IsStatus" />
                                    </td>
                                    <td class="text-center align-middle">
                                        <a title="Sửa" data-link="@Context.Request.GetRawUrl()" data-url="/LoaiCayTrong/Edit/?id=@SystemFunctions.EncodeId(d.Id)" data-toggle="modal" data-target="#modal" class="btn btn-warning btn-sm popup"><i class="fa fa-edit"></i> Sửa</a>
                                        <a title="Xóa" data-link="@Context.Request.GetRawUrl()" data-url="/LoaiCayTrong/Delete/?id=@SystemFunctions.EncodeId(d.Id)" data-toggle="modal" data-target="#modal" class="btn btn-danger btn-sm popup-delete"><i class="fa fa-trash-o" aria-hidden="true"></i> Xóa</a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td class="text-center align-middle" colspan="4"><em>Không có kết quả.</em></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix">
        @{
            if (Model.TotalRecords > Model.PageSize)
            {
                <div class="card-footer">
                    @await Component.InvokeAsync("Paging", new { page = Model })
                </div>
            }
        }
    </div>
</div>
<script>
    $(".txtOrder").on("change", function () {
        updateData($(this).data("url"), $(this).data("id"), $(this).val());
    });
    $(".chStatus").on("change", function () {
        updateData($(this).data("url"), $(this).data("id"));
    });
    $(".popup-delete").on("click", function () {
        var url = $(this).data("url");
        var id = $(this).data("id");
        var urlBack = $(this).data("link");
        $.SmartMessageBox({
            title: "Thông báo!",
            content: "Bạn muốn xóa loại cây trồng này?",
            buttons: '[Đóng][Xác nhận]'
        }, function (ButtonPressed) {
            if (ButtonPressed === "Xác nhận") {
                DeleteData(url, id, function () {
                    let element = document.getElementById('box-content');
                    loadContent(urlBack, element);
                });
            }
        });
    });
</script>